# default
spring:
  profiles:
    active: local

---
# mysql 환경도 local로 설정 default가 local이기 때문에 아무런 옵션이 없다면 해당 설정이 세팅
spring:
  config:
    activate:
      on-profile: local # default가 로컬로 설정
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false #프로젝트 실행 시 파라미터가 존재하더라도 해당 job이 실행되지 않는다.
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3305/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password1234
  jpa:
    show-sql: true

---
# test 환경은 h2 가동 (test 옵션 추가 필요)
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2